apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sep-rbs-server.fullname" . }}-config
  labels:
    {{- include "sep-rbs-server.labels" . | nindent 4 }}
data:
  SERVER_HOST: {{ .Values.server.host | quote }}
  SERVER_PORT: {{ .Values.server.port | quote }}
  SERVER_MAX_PENDING: {{ .Values.server.maxPending | quote }}
  SERVER_LISTEN_BACKLOG: {{ .Values.server.listenBacklog | quote }}
  SERVER_MAX_ACTIVE: {{ .Values.server.maxActive | quote }}
  SSL_CERT_FILE: {{ .Values.tls.certFile | quote }}
  SSL_KEY_FILE: {{ .Values.tls.keyFile | quote }}
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
